### ISSUE TITLE
As a user I want to authenticate in order to access the system

### ISSUE THREAD

**Issue by LinhNguyenLe2109** [leoschwartz/ShiftManagementTool#2]
# Description
We will implement the APIs to authenticate the user.  Log in page will be created as well. If home page has not been implemented, create an empty home page.

# Acceptance Criteria
- They should be able to be verified by entering their email and password. 
- Wrong credentials should result in an error message
- Empty input fields result in proper error message
- The application then direct the user to home page upon successful login
- Password should be encrypted

# Testing
For testing purpose, a user account will be added to the database. User email: testnewuser@gmail.com, User password: 123456
Then performs these test:
- Log in without any credential
- Log in without entering a password
- Log in without entering an email
- Log in with correct credentials
- Log in with correct email and wrong password
- Log in with wrong email and correct password

**Comment by pstaleystudent** [comment]
Backend should be working, frontend is next. Backend uses firebase-admin and requires an IdToken.
Frontend will use firebase (client) and signInWithEmailAndPassword + firebase.auth().currentUser.getIdToken to forward to backend. Fireauth accounts don't have any auxiliary information (e.g. name, type), so I need to look in to that.
Successfully auth'd with a firebase account in a test environment

**Comment by pstaleystudent** [comment]
frontend todo:
- do api fetch for token
- store token by some means:
  - local-storage : xss vulnerability
  - httponly cookie : rewrite serverside auth to use cookies, more research
- provide token on subsequent requests
- handle when token is invalid or expired

https://stackoverflow.com/questions/48983708/where-to-store-access-token-in-react-js

**Comment by pstaleystudent** [comment]
The firebase auth stuff is a mess trying to isolate the frontend from the server. None of the frontend solutions apply at all without server access, so the frontend has to implement the session stuff from scratch.

**Comment by LinhNguyenLe2109** [comment]
User with proper error will now be able to log in into the system. If the user enter wrong credentials, an alert will pop up and notify the user.

Improvement, this can be improved by adding a loading icon while verifying
