### ISSUE TITLE
Generate README files and basic front-end theme

### ISSUE THREAD

**Issue by LinhNguyenLe2109** [leoschwartz/ShiftManagementTool#3]
# Description
Generate a README that provides details about the project. This file will allow readers to understand the purpose of the project, its technology stack. It should have the following section:
- Project's Title
- Project Description
- Technology stack
- Color theme using [Coolor](https://coolors.co/) or anything similar. 

# Acceptance Criteria
- Readme file is created
- Description clearly explains the project
- Each technology provides a link to the technology's homepage for reference
- Theme is provided

**Comment by leoschwartz** [comment]
I updated the project README file and left some options for the color scheme
