### ISSUE TITLE
Set up front-end development environment

### ISSUE THREAD

**Issue by LinhNguyenLe2109** [leoschwartz/ShiftManagementTool#4]
# Description
Set up the project using React, installing it using [Vite](https://vitejs.dev/) or [Next.js](https://nextjs.org/) is strongly recommended. Integrate [Tailwind](https://tailwindcss.com/) into the application, install [Jest](https://jestjs.io/) and [Cypress](https://www.cypress.io/)

# Acceptance Criteria
- React is installed using either mentioned method
- Tailwind is integrated
  - Breakpoint is configured (normally its smallest breakpoint is 600, we can have more for flexibility such as xs: 420, 2xs: 320 and 3xs: 280)
  - Custom theme is integrated (generate a css name which store all the variables, assign it to custom variable in tailwind. This will help in the future if we want dark mode)
- There should be at least one test for jest and 1 test for cypress

# Testing
- Fetch the project
- Run the project locally
- The loaded page should have at least a text with Tailwind styling
- Jest test result is printed
- Cypress result is printed

**Comment by leoschwartz** [comment]
Finished setting up the front end dev environment, only the theme color variables are pending
