### ISSUE TITLE
Shift Scheduling Backend Design

### ISSUE THREAD

**Issue by pstaleystudent** [leoschwartz/ShiftManagementTool#44]
# Description
Shifts are comprised of at least two objects: the event/shift and the schedule. Couple things to iron out:
- How much to we care about shifts getting desynced from the schedule object? Do we need to track schedule changes?
- We need the association for the editing eventually, but should it ever detach? Ties into the UI; if a manager edits a shift that's part of a schedule, what should happen when the schedule changes? What if the changes _conflict_?
- When should shift objects begin their existence? They need to exist at time of editing, completing, or missing. Should they only be created when the shift is completed/missed/edited? Should they be created when they are upcoming by x weeks? If the latter, does that prevent managers from editing shifts in the future?

# Acceptance Criteria
- Team members are in agreement.
- Documented.

**Comment by pstaleystudent** [comment]
![Schema (2)](https://github.com/leoschwartz/ShiftManagementTool/assets/75087815/c4f78e02-1fc1-4810-aa43-479367281c00)
Relevant section of the old class diagram.

**Comment by pstaleystudent** [comment]
Generate records 3 weeks? in advance.
When a shift is updated, the shift is flagged as edited. When you update a shift template, you are given the option to override existing edits or ignore edited changes.

**Comment by LinhNguyenLe2109** [comment]
![image](https://github.com/leoschwartz/ShiftManagementTool/assets/90426807/e5d9a248-6bcf-4942-883a-e071b9117bda)
![image](https://github.com/leoschwartz/ShiftManagementTool/assets/90426807/59f36e3f-0b92-48bf-b0a6-71df2b48e449)
