### ISSUE TITLE
Create database design

### ISSUE THREAD

**Issue by LinhNguyenLe2109** [leoschwartz/ShiftManagementTool#6]
# Description
Using [draw.io](https://app.diagrams.net/) or [Visual Paradigm](https://www.visual-paradigm.com/) or anything as such, design the database for the application. The design should show the all the properties for each class, show the relation between classes and how one class can reference another one if they are related. Each shift contains a form that allow manager to assess employee's performance for each shift.

# Acceptance Criteria
- Minimum: User class design, schedule class and performance class are created
- There are 3 types of users: Administrator, Manager and Employees. Manager can create a schedule for employees, employee can only assign, drop shifts. Manager can generate shifts for employee. Administrator can only generate Manger account. Only employees have shifts, others don't
- Shift show would created, who is assigned, time, location, department(optional) and note
- Form class includes data about the employee performance, a form is generated only when manager want to assess employee's performance relating to that specific shift

**Comment by pstaleystudent** [comment]
Uploaded to teams. 
ASSUMPTIONS:
There was literally no documentation on how scheduling shifts worked, so:
	1. Scheduled on a weekdays/times basis. 
	2. We don't handle the idea of partial completion.
	3. I'm not sure what the plan is on emails, but I think we should log them.
	    Should probably add something to log what triggered them as well.
	4. No idea what shift reviews are going to look like. Placeholder.
	5. I'm not actually sure what the firestore datatypes are called. I went off this: https://cloud.google.com/firestore/docs/concepts/data-types
	
Should be reviewed by someone else

**Comment by pstaleystudent** [comment]
Something I missed: we need to track who/when unassigned shifts, and the reassigning and all that.
